Лабоарторна робота 1 Гончар Назар ФІТ 4-8 Варіант 7

In [ ]:
import numpy as np

1. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(3, 2))
matrix2 = np.random.randint(1, 11, size=(2, 4))

print("Matrix 1 (3x2):")
print(matrix1)

print("\nMatrix 2 (2x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (3x4):")
print(result)

Matrix 1 (3x2):
[[ 2 10]
 [ 6  3]
 [ 4  1]]

Matrix 2 (2x4):
[[5 3 7 6]
 [1 5 6 7]]

Result of matrix multiplication (3x4):
[[20 56 74 82]
 [33 33 60 57]
 [21 17 34 31]]


2. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 2))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x2):")
print(result)

Matrix 1 (2x3):
[[2 1 1]
 [2 4 5]]

Matrix 2 (3x2):
[[2 4]
 [3 4]
 [2 2]]

Result of matrix multiplication (2x2):
[[ 9 14]
 [26 34]]


3. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами
в діапазоні від 1 до 7 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 8, size=(4, 2))
matrix2 = np.random.randint(1, 8, size=(2, 5))

print("Matrix 1 (4x2):")
print(matrix1)

print("\nMatrix 2 (2x5):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (4x5):")
print(result)

Matrix 1 (4x2):
[[2 1]
 [2 2]
 [5 4]
 [1 1]]

Matrix 2 (2x5):
[[7 7 5 1 1]
 [4 5 5 3 4]]

Result of matrix multiplication (4x5):
[[18 19 15  5  6]
 [22 24 20  8 10]
 [51 55 45 17 21]
 [11 12 10  4  5]]


4. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x3):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x3):")
print(result)

Matrix 1 (2x3):
[[4 1 5]
 [5 2 5]]

Matrix 2 (3x3):
[[4 1 4]
 [2 3 2]
 [5 1 1]]

Result of matrix multiplication (2x3):
[[43 12 23]
 [49 16 29]]


5. Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 8 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 9, size=(3, 2))
matrix2 = np.random.randint(1, 9, size=(2, 2))

print("Matrix 1 (3x2):")
print(matrix1)

print("\nMatrix 2 (2x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (3x2):")
print(result)

Matrix 1 (3x2):
[[4 3]
 [5 2]
 [2 1]]

Matrix 2 (2x2):
[[5 8]
 [6 3]]

Result of matrix multiplication (3x2):
[[38 41]
 [37 46]
 [16 19]]


6. Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 4))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x4):")
print(result)

Matrix 1 (2x3):
[[2 3 4]
 [4 3 5]]

Matrix 2 (3x4):
[[4 5 5 4]
 [3 5 3 3]
 [2 4 4 2]]

Result of matrix multiplication (2x4):
[[25 41 35 25]
 [35 55 49 35]]


7. Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 6 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 7, size=(4, 2))
matrix2 = np.random.randint(1, 7, size=(2, 2))

print("Matrix 1 (4x2):")
print(matrix1)

print("\nMatrix 2 (2x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (4x2):")
print(result)

Matrix 1 (4x2):
[[2 3]
 [6 3]
 [2 5]
 [2 5]]

Matrix 2 (2x2):
[[4 3]
 [2 1]]

Result of matrix multiplication (4x2):
[[14  9]
 [30 21]
 [18 11]
 [18 11]]


8. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 5, size=(2, 3))
matrix2 = np.random.randint(1, 5, size=(3, 3))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x3):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x3):")
print(result)

Matrix 1 (2x3):
[[4 4 2]
 [3 2 2]]

Matrix 2 (3x3):
[[2 4 4]
 [3 2 2]
 [1 1 2]]

Result of matrix multiplication (2x3):
[[22 26 28]
 [14 18 20]]


9. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 10 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 11, size=(3, 2))
matrix2 = np.random.randint(1, 11, size=(2, 4))

print("Matrix 1 (3x2):")
print(matrix1)

print("\nMatrix 2 (2x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (3x4):")
print(result)

Matrix 1 (3x2):
[[10  1]
 [ 5  8]
 [ 5  9]]

Matrix 2 (2x4):
[[ 3  7  5  9]
 [ 2  9 10  7]]

Result of matrix multiplication (3x4):
[[ 32  79  60  97]
 [ 31 107 105 101]
 [ 33 116 115 108]]


10. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 2))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x2):")
print(result)

Matrix 1 (2x3):
[[3 4 2]
 [2 3 4]]

Matrix 2 (3x2):
[[4 2]
 [2 3]
 [4 2]]

Result of matrix multiplication (2x2):
[[28 22]
 [30 21]]


11. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами
в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(4, 2))
matrix2 = np.random.randint(1, 11, size=(2, 5))

print("Matrix 1 (4x2):")
print(matrix1)

print("\nMatrix 2 (2x5):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (4x5):")
print(result)

Matrix 1 (4x2):
[[ 2  3]
 [ 7  4]
 [ 5  4]
 [10 10]]

Matrix 2 (2x5):
[[ 8  8 10  1  8]
 [ 7  3 10  1  5]]

Result of matrix multiplication (4x5):
[[ 37  25  50   5  31]
 [ 84  68 110  11  76]
 [ 68  52  90   9  60]
 [150 110 200  20 130]]


12. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x3):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x3):")
print(result)

Matrix 1 (2x3):
[[4 3 4]
 [5 2 5]]

Matrix 2 (3x3):
[[5 3 1]
 [3 3 3]
 [2 4 1]]

Result of matrix multiplication (2x3):
[[37 37 17]
 [41 41 16]]


13. Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 8 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 9, size=(3, 2))
matrix2 = np.random.randint(1, 9, size=(2, 2))

print("Matrix 1 (3x2):")
print(matrix1)

print("\nMatrix 2 (2x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (3x2):")
print(result)

Matrix 1 (3x2):
[[6 1]
 [4 8]
 [4 6]]

Matrix 2 (2x2):
[[4 7]
 [6 6]]

Result of matrix multiplication (3x2):
[[30 48]
 [64 76]
 [52 64]]


14. Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 4))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x4):")
print(result)

Matrix 1 (2x3):
[[4 5 3]
 [3 5 5]]

Matrix 2 (3x4):
[[4 2 5 4]
 [1 5 2 3]
 [3 1 4 4]]

Result of matrix multiplication (2x4):
[[30 36 42 43]
 [32 36 45 47]]


15. Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 3 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 4, size=(4, 2))
matrix2 = np.random.randint(1, 4, size=(2, 2))

print("Matrix 1 (4x2):")
print(matrix1)

print("\nMatrix 2 (2x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (4x2):")
print(result)

Matrix 1 (4x2):
[[3 2]
 [3 3]
 [3 1]
 [3 1]]

Matrix 2 (2x2):
[[3 1]
 [1 2]]

Result of matrix multiplication (4x2):
[[11  7]
 [12  9]
 [10  5]
 [10  5]]


16. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 5, size=(2, 3))
matrix2 = np.random.randint(1, 5, size=(3, 3))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x3):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x3):")
print(result)

Matrix 1 (2x3):
[[1 1 1]
 [1 3 2]]

Matrix 2 (3x3):
[[2 1 2]
 [4 1 1]
 [1 3 2]]

Result of matrix multiplication (2x3):
[[ 7  5  5]
 [16 10  9]]


17. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 5, size=(3, 2))
matrix2 = np.random.randint(1, 5, size=(2, 4))

print("Matrix 1 (3x2):")
print(matrix1)

print("\nMatrix 2 (2x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (3x4):")
print(result)

Matrix 1 (3x2):
[[1 2]
 [3 1]
 [1 1]]

Matrix 2 (2x4):
[[1 1 2 2]
 [4 3 1 1]]

Result of matrix multiplication (3x4):
[[9 7 4 4]
 [7 6 7 7]
 [5 4 3 3]]


18. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 2))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x2):")
print(result)

Matrix 1 (2x3):
[[4 1 4]
 [2 5 4]]

Matrix 2 (3x2):
[[5 1]
 [2 4]
 [3 5]]

Result of matrix multiplication (2x2):
[[34 28]
 [32 42]]


19. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами
в діапазоні від 1 до 6 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 7, size=(4, 2))
matrix2 = np.random.randint(1, 7, size=(2, 5))

print("Matrix 1 (4x2):")
print(matrix1)

print("\nMatrix 2 (2x5):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (4x5):")
print(result)

Matrix 1 (4x2):
[[1 5]
 [3 1]
 [4 3]
 [3 1]]

Matrix 2 (2x5):
[[5 3 6 6 2]
 [2 5 4 1 3]]

Result of matrix multiplication (4x5):
[[15 28 26 11 17]
 [17 14 22 19  9]
 [26 27 36 27 17]
 [17 14 22 19  9]]


20. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 5, size=(2, 3))
matrix2 = np.random.randint(1, 5, size=(3, 3))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x3):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x3):")
print(result)

Matrix 1 (2x3):
[[1 2 3]
 [1 4 1]]

Matrix 2 (3x3):
[[1 1 1]
 [3 1 4]
 [4 2 4]]

Result of matrix multiplication (2x3):
[[19  9 21]
 [17  7 21]]


21. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x3):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x3):")
print(result)

Matrix 1 (2x3):
[[4 5 5]
 [2 5 3]]

Matrix 2 (3x3):
[[2 5 1]
 [4 1 3]
 [3 1 5]]

Result of matrix multiplication (2x3):
[[43 30 44]
 [33 18 32]]


22. Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 8 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 9, size=(3, 2))
matrix2 = np.random.randint(1, 9, size=(2, 2))

print("Matrix 1 (3x2):")
print(matrix1)

print("\nMatrix 2 (2x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (3x2):")
print(result)

Matrix 1 (3x2):
[[3 5]
 [1 1]
 [6 5]]

Matrix 2 (2x2):
[[1 3]
 [2 6]]

Result of matrix multiplication (3x2):
[[13 39]
 [ 3  9]
 [16 48]]


23. Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 7 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 8, size=(2, 3))
matrix2 = np.random.randint(1, 8, size=(3, 4))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x4):")
print(result)

Matrix 1 (2x3):
[[4 5 6]
 [5 4 2]]

Matrix 2 (3x4):
[[7 6 1 1]
 [1 2 5 6]
 [2 5 4 4]]

Result of matrix multiplication (2x4):
[[45 64 53 58]
 [43 48 33 37]]


24. Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 6 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 7, size=(4, 2))
matrix2 = np.random.randint(1, 7, size=(2, 2))

print("Matrix 1 (4x2):")
print(matrix1)

print("\nMatrix 2 (2x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (4x2):")
print(result)

Matrix 1 (4x2):
[[4 3]
 [5 1]
 [5 1]
 [6 5]]

Matrix 2 (2x2):
[[4 2]
 [3 1]]

Result of matrix multiplication (4x2):
[[25 11]
 [23 11]
 [23 11]
 [39 17]]


25. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x3):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x3):")
print(result)

26. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(3, 2))
matrix2 = np.random.randint(1, 6, size=(2, 4))

print("Matrix 1 (3x2):")
print(matrix1)

print("\nMatrix 2 (2x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (3x4):")
print(result)

Matrix 1 (3x2):
[[4 1]
 [2 4]
 [3 5]]

Matrix 2 (2x4):
[[2 2 1 4]
 [5 4 1 5]]

Result of matrix multiplication (3x4):
[[13 12  5 21]
 [24 20  6 28]
 [31 26  8 37]]


27. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 7 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 8, size=(2, 3))
matrix2 = np.random.randint(1, 8, size=(3, 2))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x2):")
print(result)

Matrix 1 (2x3):
[[3 6 6]
 [3 5 2]]

Matrix 2 (3x2):
[[1 4]
 [4 1]
 [1 7]]

Result of matrix multiplication (2x2):
[[33 60]
 [25 31]]


28. Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 4 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 5, size=(2, 3))
matrix2 = np.random.randint(1, 5, size=(3, 4))

print("Matrix 1 (2x3):")
print(matrix1)

print("\nMatrix 2 (3x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (2x4):")
print(result)

Matrix 1 (2x3):
[[3 1 2]
 [1 2 1]]

Matrix 2 (3x4):
[[3 4 4 1]
 [3 1 2 4]
 [1 4 4 4]]

Result of matrix multiplication (2x4):
[[14 21 22 15]
 [10 10 12 13]]


29. Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 3 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 4, size=(4, 2))
matrix2 = np.random.randint(1, 4, size=(2, 2))

print("Matrix 1 (4x2):")
print(matrix1)

print("\nMatrix 2 (2x2):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (4x2):")
print(result)

Matrix 1 (4x2):
[[3 1]
 [2 1]
 [3 2]
 [1 3]]

Matrix 2 (2x2):
[[2 1]
 [1 3]]

Result of matrix multiplication (4x2):
[[ 7  6]
 [ 5  5]
 [ 8  9]
 [ 5 10]]


30. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 10 та перемножте їх між собою.


In [ ]:
matrix1 = np.random.randint(1, 11, size=(3, 2))
matrix2 = np.random.randint(1, 11, size=(2, 4))

print("Matrix 1 (3x2):")
print(matrix1)

print("\nMatrix 2 (2x4):")
print(matrix2)

result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication (3x4):")
print(result)

Matrix 1 (3x2):
[[4 7]
 [7 9]
 [6 4]]

Matrix 2 (2x4):
[[ 3  7  4  5]
 [ 4  4 10 10]]

Result of matrix multiplication (3x4):
[[ 40  56  86  90]
 [ 57  85 118 125]
 [ 34  58  64  70]]
